import { Component, OnInit } from '@angular/core';
import { AbstractChildComponent } from 'src/app/components/view-stack/abstract-child-component';
import { ApAssetComponent } from '../ap-asset.component';
import { FormGroup, FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-ap-asset-entry',
  templateUrl: './ap-asset-entry.component.html',
  styleUrls: ['./ap-asset-entry.component.scss']
})
export class ApAssetEntryComponent extends AbstractChildComponent<ApAssetComponent> implements OnInit {

  assetForm: FormGroup;

  constructor(
    private fb: FormBuilder,
  ) {
    super();

  }

  ngOnInit() {
    this.initForm();
  }

  initForm() {
    this.assetForm = this.fb.group({
      assetId: [''],
      createDate: [''],
      createStaffCode: [''],
      updateDate: [''],
      updateStaffCode: [''],
      version: [''],
      apGetTanLineAstId: [''],
      apGetTanLineAstLineSeq: [''],
      updateComment: [''],
      eappId: [''],
      apStatus: [''],
      apStatusName: [''],
      apDate: [''],
      apCreateStaffCode: [''],
      apCreateStaffName: [''],
      apCreateCompanyCode: [''],
      apCreateCompanyName: [''],
      apCreateSectionCode: [''],
      apCreateSectionYear: [''],
      apCreateSectionName: [''],
      apStaffCode: [''],
      apStaffName: [''],
      apCompanyCode: [''],
      apCompanyName: [''],
      apSectionCode: [''],
      apSectionYear: [''],
      apSectionName: [''],
      apTel: [''],
      apOfficeName: [''],
      astName: [''],
      astCategory1Code: [''],
      astCategory1Name: [''],
      astCategory2Code: [''],
      astCategory2Name: [''],
      astQuantityManageType: [''],
      astSerialManageType: [''],
      astShapeCode: [''],
      astShapeName: [''],
      astMakerCode: [''],
      astMakerName: [''],
      astShopName: [''],
      astMakerModel: [''],
      astSerialCode: [''],
      astGuaranteeTermDate: [''],
      astGetType: [''],
      astGetTypeName: [''],
      astSystemSectionDeployFlag: [''],
      astSystemSectionDeployFlagName: [''],
      astAssetType: [''],
      astAssetTypeName: [''],
      astHolderCode: [''],
      astHolderName: [''],
      astManageType: [''],
      astManageTypeName: [''],
      astOirEnable: [''],
      astOir: [''],
      astManageEndDate: [''],
      holCompanyCode: [''],
      holCompanyName: [''],
      holSectionCode: [''],
      holSectionYear: [''],
      holSectionName: [''],
      holStaffCode: [''],
      holStaffName: [''],
      holOfficeCode: [''],
      holOfficeName: [''],
      holOfficeFloor: [''],
      holOfficeRoomNum: [''],
      holOfficeRackNum: [''],
      holPurposeCode: [''],
      holPurposeName: [''],
      holOfficeDescription: [''],
      holGetStaffCode: [''],
      holGetStaffName: [''],
      holGetCompanyCode: [''],
      holGetCompanyName: [''],
      holGetSectionCode: [''],
      holGetSectionYear: [''],
      holGetSectionName: [''],
      holGetDate: [''],
      holQuantity: [''],
      useCompanyCode: [''],
      useCompanyName: [''],
      useSectionCode: [''],
      useSectionYear: [''],
      useSectionName: [''],
      useStaffCode: [''],
      useStaffName: [''],
      useStaffCompanyCode: [''],
      useStaffCompanyName: [''],
      useStaffSectionCode: [''],
      useStaffSectionYear: [''],
      useStaffSectionName: [''],
      useStartDate: [''],
      useCommonFlag: [''],
      useCommonFlagName: [''],
      netHostName: [''],
      netEguardPermitType: [''],
      mntContractCode: [''],
      mntContractCompanyName: [''],
      mntContractStartDate: [''],
      mntContractEndDate: [''],
      mntContractAmount: [''],
      mntContractRegistCode: [''],
      mntContractRegistDate: [''],
      mntContractStaffCode: [''],
      mntContractStaffName: [''],
      mntContractServiceLevel: [''],
      mntContractDescription: [''],
      mntContractCode2: [''],
      mntContractCompanyName2: [''],
      mntContractStartDate2: [''],
      mntContractEndDate2: [''],
      mntContractAmount2: [''],
      mntContractRegistCode2: [''],
      mntContractRegistDate2: [''],
      mntContractStaffCode2: [''],
      mntContractStaffName2: [''],
      mntContractServiceLevel2: [''],
      mntContractDescription2: [''],
      mntContractCode3: [''],
      mntContractCompanyName3: [''],
      mntContractStartDate3: [''],
      mntContractEndDate3: [''],
      mntContractAmount3: [''],
      mntContractRegistCode3: [''],
      mntContractRegistDate3: [''],
      mntContractStaffCode3: [''],
      mntContractStaffName3: [''],
      mntContractServiceLevel3: [''],
      mntContractDescription3: [''],
      dscDescription: [''],
      dscAttribute1: [''],
      dscAttribute2: [''],
      dscAttribute3: [''],
      dscAttribute4: [''],
      dscAttribute5: [''],
      dscAttribute6: [''],
      dscAttribute7: [''],
      dscAttribute8: [''],
      dscAttribute9: [''],
      dscAttribute10: [''],
      dscAttribute11: [''],
      dscAttribute12: [''],
      dscAttribute13: [''],
      dscAttribute14: [''],
      dscAttribute15: [''],
      dscAttribute16: [''],
      dscAttribute17: [''],
      dscAttribute18: [''],
      dscAttribute19: [''],
      dscAttribute20: [''],
      dscFailureAssetId: [''],
      invInCompanyActualFlag: [''],
      invInCompanyActualFlagName: [''],
      invBarcode: [''],
      invSealIssueFlag: [''],
      invSealIssueFlagName: [''],
      invSealIssueDate: [''],
      invSealIssueDescription: [''],
      deleteFlag: [''],
      deleteDate: [''],
      deleteReason: [''],
      getApplicationId: [''],
      registApplicationId: [''],
      contractNum: [''],
      dreamsNum: [''],
      parentAssetId: [''],
      apCreateTel: [''],
      contractEda: [''],
      shisanNum: [''],
      koyunoL: [''],
      koyunoF: [''],
    });
  }

}
